CREATE DATABASE DBPROJETODSI201;

USE DBPROJETODSI201;

CREATE TABLE EMPRESA(
	CDEMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NMEMPRESA VARCHAR(255),
    CNPJEMPRESA VARCHAR(255),
    SENHAEMPRESA VARCHAR(255),
    RAMOEMPRESA VARCHAR(255)
);
